stages:
  - install
  - lint
  - test
  - build
  - deploy

variables:
  NODE_ENV: "production"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bun
    - node_modules/
    - code/**/node_modules/

install:
  stage: install
  image: oven/bun:1.2.7
  script:
    - bun --version
    - bun install

lint:
  stage: lint
  image: oven/bun:1.2.7
  script:
    - bun install
    - bun run lint

test:
  stage: test
  image: oven/bun:1.2.7
  script:
    - bun install
    - bun run test

build:
  stage: build
  image: oven/bun:1.2.7
  script:
    - bun install
    - bun run build

deploy:staging:
  stage: deploy
  image: oven/bun:1.2.7
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  before_script:
    - apt-get update && apt-get install -y zip python3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - export STAGE=stg
    - bun install
    - bun infrastructure/scripts/migrate.ts
    - bash infrastructure/scripts/deploy-api.sh
    - bash infrastructure/scripts/deploy-crons.sh
    - bash infrastructure/scripts/deploy-assets.sh
    - bash infrastructure/scripts/deploy-front-user.sh
    - bash infrastructure/scripts/deploy-front-admin.sh

deploy:production:
  stage: deploy
  image: oven/bun:1.2.7
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  before_script:
    - apt-get update && apt-get install -y zip python3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - export STAGE=prd
    - bun install
    - bun infrastructure/scripts/migrate.ts
    - bash infrastructure/scripts/deploy-api.sh
    - bash infrastructure/scripts/deploy-crons.sh
    - bash infrastructure/scripts/deploy-assets.sh
    - bash infrastructure/scripts/deploy-front-user.sh
    - bash infrastructure/scripts/deploy-front-admin.sh

